### ISSUE TITLE
Library Metadata Additions

### ISSUE THREAD

**Issue by patrick-lloyd-ray** [brain-bican/metadata-schemas#36]
Per request from Rashmie, the following are requested additions to the library metadata schema:

- [x] dissociated_cell_sample_preparation_date
- [x] dissociated_cell_sample_cell_label_barcode
- [x] enriched_cell_sample_cell_label_barcode
- [x] enriched_cell_sample_preparation_date
- [x] histone_modification_marker
- [x] library_pool_preparation_date
- [x] flowcell

If @hongna2008 and team approve these, I can add them to the schema and update.

**Comment by hongna2008** [comment]
I will check this with Jim.

Thanks,

Na

**Comment by KimberlySmithAllen** [comment]
These fields were part of the final LMM data list and are already in the SeqLib Portal.  They need to be approved.
Kim

**Comment by hongna2008** [comment]
Hi, Patrick and Kim,

These are new data elements to your last version. More information is
needed to complete the data elements definition. I am copying this request
to Jim and Hua, they may directly response to this request.

Thank you for maintaining this metadata.

Na

**Comment by hongna2008** [comment]
Hi, Kim,

For the request below,


******

Per request from Rashmie, the following are requested additions to the library metadata schema:

  *   dissociated_cell_sample_preparation_date
  *   dissociated_cell_sample_cell_label_barcode
  *   enriched_cell_sample_cell_label_barcode
  *   enriched_cell_sample_preparation_date
  *   histone_modification_marker
  *   library_pool_preparation_date
  *   flowcell
********

Is this part of the coordinated effort you and GQ’s team worked on? Are these elements added to your current work with GQ’s team after the final release from the L2M task force? Are these elements in the SeqPortal already? We just want to make sure that these metadata elements are coordinated effort and are not in conflict or redundant with what you guys are currently working on.

Also, alone the line of how we should maintain the library minimal metadata for future update, we propose to let you to be the owner for any future update evaluation and approval, since you are actively continuing this line of work. Would that be ok with you? I think having one owner who has the working knowledge would be appropriate, and we need to have this explicitly decided so that the process of update would be clear.

Thanks,

Jim

--
W. Jim Zheng, Ph.D., Professor
Founding Director, Data Science and Informatics Core for Cancer Research
Director, Bioinformatics and High-Performance Computing Service Center
Associate Director, Translational Excellence and Application in Medicine – Artificial Intelligence

[Text  Description automatically generated with medium confidence]
7000 Fannin St | Suite 600 | Houston, Texas, 77030
Phone: (713) 500-3641 | Email: ***@***.******@***.***>
https://sbmi.uth.edu/faculty-and-staff/jim-zheng.htm
https://sbmi.uth.edu/dsiccr/
https://sbmi.uth.edu/bioinformatics/index.htm


From: Na Hong ***@***.***>
Date: Thursday, March 14, 2024 at 4:49 PM
To: brain-bican/metadata-schemas ***@***.***>
Cc: Mention ***@***.***>, brain-bican/metadata-schemas ***@***.***>, ***@***.*** ***@***.***>, ***@***.*** ***@***.***>, Zheng, Wenjin J ***@***.***>
Subject: Re: [brain-bican/metadata-schemas] Library Metadata Additions (Issue #36)
External: Increase caution when handling links and attachments.

Hi, Patrick and Kim,

These are new data elements to your last version. More information is needed to complete the data elements definition. I am copying this request to Jim and Hua, they may directly response to this request.

Thank you for maintaining this metadata.

Na

On Thu, Mar 14, 2024 at 16:13 Patrick Lloyd Ray ***@***.******@***.***>> wrote:

Per request from Rashmie, the following are requested additions to the library metadata schema:

  *   dissociated_cell_sample_preparation_date
  *   dissociated_cell_sample_cell_label_barcode
  *   enriched_cell_sample_cell_label_barcode
  *   enriched_cell_sample_preparation_date
  *   histone_modification_marker
  *   library_pool_preparation_date
  *   flowcell

If @hongna2008<https://github.com/hongna2008> and team approve these, I can add them to the schema and update.

**Comment by hongna2008** [comment]
Hi Jim –

Thank you for proposing that I be the owner for evaluating and approving LMM edits.  I think this is appropriate and would be happy to take on this role.  I agree this will help with clarity in managing this list.

Yes, these elements are part of the coordinated effort with GQ’s team and are already in the SeqPortal.
I support their approval.

4 of these elements were part of the final LMM v4.2_230920 (see table below).
2 additional date fields have been added to the Portal.
And the final Flowcell field is produced after sequencing, so wasn’t part of the original scope of the LMM (tissue to pool).

Field Name
Definition/Description
Data Example
Identifier/Metadata
Data Type
Required/Optional for Analysis
Required/Optional for Tracking
Allow Null Value
Required for Alignment
SubGroup
Dissociated cell source barcode name
Name of oligo used in cell plexing.  The oligo will tag allow separate dissociated cell samples to be combined downstream in the barcoded cell sample.  The oligo name is associated with a sequence in a lookup table.  This sequence will be needed to during analysis, after alignment, to associate reads with parent dissociated cell sample.
CMO301
Metadata
ValueSet
Required
Optional
Allowed
No
Dissociated cell sample
Enriched cell source barcode name
Name of molecular barcode used to individual Enriched Cell Source to allow for pooling of Enriched Cell Sources before 10x load (Barcoding Cell step) [aka 1st round barcodes]
1,2 - CPU, H3K27ac
3,4 - HYP, H3K27ac
5,6 - HCa, H3K27ac
7,8 - HCp, H3K27ac (#7 has 10% Hela Spike-in)
9,10 - CPU, H3K27me3
11,12 - HYP, H3K27me3
13,14 - HCa, H3K27me3
15,16 - HCp, H3K27me3
Metadata
ValueSet
Optional
Optional
Allowed
Yes
Enriched cell sample
Histone modification marker
Histone modification marker antibodies (eg H3K27ac, H3K27me3, H3K9me3) used in conjunction with an Enriched Cell Source Barcode in order to combine multiple Enriched Cell Populations before Barcoded Cell Sample step for 10xMultiome method.  Each of the Histone antibodies captures an essential part of the epigenome.
H3K27ac (Abcam,ab4729, Lot: GR3416787-1),
H3K27me3 (Abcam,ab4729, Lot: GR3416787-1)
Metadata
Text
Optional
Optional
Allowed
No
Enriched cell sample
Library construction date
Date of library construction
12/9/2021
Metadata
Date
Optional
Optional
Allowed
No
Library

Let me know if you have further questions!
Thanks,
Kim

**Comment by hongna2008** [comment]
Thanks a lot, Kim. We really appreciate that you agree to take on the role to manage future updates.

Since those four elements are already in the final version we released, I assume that we don’t really need to approve them.

For the other three elements, maybe we can count them as the update after the L2M task force scope (as we already wrapped up the L2M Task Force), and add them to what Patrick’s group is managing. That way, we maintain things consistently. Please let me know what you guys think @Kim, @Patrick ***@***.***>

Best,

Jim

--
W. Jim Zheng, Ph.D., Professor
Founding Director, Data Science and Informatics Core for Cancer Research
Director, Bioinformatics and High-Performance Computing Service Center
Associate Director, Translational Excellence and Application in Medicine – Artificial Intelligence

[Text  Description automatically generated with medium confidence]
7000 Fannin St | Suite 600 | Houston, Texas, 77030
Phone: (713) 500-3641 | Email: ***@***.******@***.***>
https://sbmi.uth.edu/faculty-and-staff/jim-zheng.htm
https://sbmi.uth.edu/dsiccr/
https://sbmi.uth.edu/bioinformatics/index.htm


From: Kimberly Smith ***@***.***>
Date: Friday, March 15, 2024 at 11:17 AM
To: Zheng, Wenjin J ***@***.***>
Cc: Mention ***@***.***>, hua.xu ***@***.***>, ***@***.*** ***@***.***>, brain-bican/metadata-schemas ***@***.***>, Patrick Ray ***@***.***>, Lydia Ng ***@***.***>, Kimberly Smith ***@***.***>
Subject: RE: [brain-bican/metadata-schemas] Library Metadata Additions (Issue #36)
External: Increase caution when handling links and attachments.

Hi Jim –

Thank you for proposing that I be the owner for evaluating and approving LMM edits.  I think this is appropriate and would be happy to take on this role.  I agree this will help with clarity in managing this list.

Yes, these elements are part of the coordinated effort with GQ’s team and are already in the SeqPortal.
I support their approval.

4 of these elements were part of the final LMM v4.2_230920 (see table below).
2 additional date fields have been added to the Portal.
And the final Flowcell field is produced after sequencing, so wasn’t part of the original scope of the LMM (tissue to pool).

Field Name
Definition/Description
Data Example
Identifier/Metadata
Data Type
Required/Optional for Analysis
Required/Optional for Tracking
Allow Null Value
Required for Alignment
SubGroup
Dissociated cell source barcode name
Name of oligo used in cell plexing.  The oligo will tag allow separate dissociated cell samples to be combined downstream in the barcoded cell sample.  The oligo name is associated with a sequence in a lookup table.  This sequence will be needed to during analysis, after alignment, to associate reads with parent dissociated cell sample.
CMO301
Metadata
ValueSet
Required
Optional
Allowed
No
Dissociated cell sample
Enriched cell source barcode name
Name of molecular barcode used to individual Enriched Cell Source to allow for pooling of Enriched Cell Sources before 10x load (Barcoding Cell step) [aka 1st round barcodes]
1,2 - CPU, H3K27ac
3,4 - HYP, H3K27ac
5,6 - HCa, H3K27ac
7,8 - HCp, H3K27ac (#7 has 10% Hela Spike-in)
9,10 - CPU, H3K27me3
11,12 - HYP, H3K27me3
13,14 - HCa, H3K27me3
15,16 - HCp, H3K27me3
Metadata
ValueSet
Optional
Optional
Allowed
Yes
Enriched cell sample
Histone modification marker
Histone modification marker antibodies (eg H3K27ac, H3K27me3, H3K9me3) used in conjunction with an Enriched Cell Source Barcode in order to combine multiple Enriched Cell Populations before Barcoded Cell Sample step for 10xMultiome method.  Each of the Histone antibodies captures an essential part of the epigenome.
H3K27ac (Abcam,ab4729, Lot: GR3416787-1),
H3K27me3 (Abcam,ab4729, Lot: GR3416787-1)
Metadata
Text
Optional
Optional
Allowed
No
Enriched cell sample
Library construction date
Date of library construction
12/9/2021
Metadata
Date
Optional
Optional
Allowed
No
Library

Let me know if you have further questions!
Thanks,
Kim

**Comment by hongna2008** [comment]
I'm happy to add these to the metadata standard. I think I have all that I need to update it from here.

I may ask for help with 'flowcell' to make sure that it conforms with shared understanding of the concept. But I'll do that on GitHub (and tag you, Kim).

Best,

Patrick


Patrick L. Ray, Ph.D.

Ontologist

Allen Institute for Brain Science

T:   206.516.6431

M:  206.548.7099

E:  ***@***.******@***.***>

brainscience.alleninstitute.org
brain-map.org<https://brain-map.org/>

________________________________

**Comment by hongna2008** [comment]
Hi, Patrick and Kim,

Great, thanks a lot.

Please do not hesitate to contact us if we can be of any help with future update.

Best,

Jim

--
W. Jim Zheng, Ph.D., Professor
Founding Director, Data Science and Informatics Core for Cancer Research
Director, Bioinformatics and High-Performance Computing Service Center
Associate Director, Translational Excellence and Application in Medicine – Artificial Intelligence

[Text  Description automatically generated with medium confidence]
7000 Fannin St | Suite 600 | Houston, Texas, 77030
Phone: (713) 500-3641 | Email: ***@***.******@***.***>
https://sbmi.uth.edu/faculty-and-staff/jim-zheng.htm
https://sbmi.uth.edu/dsiccr/
https://sbmi.uth.edu/bioinformatics/index.htm


From: Patrick Ray ***@***.***>
Date: Friday, March 15, 2024 at 2:39 PM
To: Zheng, Wenjin J ***@***.***>, Kimberly Smith ***@***.***>
Cc: Mention ***@***.***>, hua.xu ***@***.***>, ***@***.*** ***@***.***>, brain-bican/metadata-schemas ***@***.***>, Lydia Ng ***@***.***>
Subject: Re: [brain-bican/metadata-schemas] Library Metadata Additions (Issue #36)
External: Increase caution when handling links and attachments.

I'm happy to add these to the metadata standard. I think I have all that I need to update it from here.

I may ask for help with 'flowcell' to make sure that it conforms with shared understanding of the concept. But I'll do that on GitHub (and tag you, Kim).

Best,

Patrick


Patrick L. Ray, Ph.D.

Ontologist

Allen Institute for Brain Science

T:   206.516.6431

M:  206.548.7099

E:  ***@***.******@***.***>

brainscience.alleninstitute.org
brain-map.org<https://brain-map.org/>

________________________________
